const SIDEBAR_PANE_TITLE: &str = "opensessions-sidebar";
const SIDEBAR_WIDTH_OPTION: &str = "@opensessions_width";

/// Array index opensessions writes its tmux hooks into.
///
/// tmux hooks are array options, and `set-hook -g <hook> <cmd>` without an
/// index replaces the whole array, wiping entries other plugins installed on
/// the same event. Writing into one fixed, unlikely slot lets opensessions
/// coexist with them and only ever touch its own entry. Keep in sync with
/// `HOOK_SLOT` in `integrations/tmux-plugin/scripts/uninstall.sh`.
pub const HOOK_SLOT: u32 = 90210;

/// The `<hook>[<slot>]` option name opensessions owns for `hook`.
pub fn hook_slot(hook: &str) -> String {
    format!("{hook}[{HOOK_SLOT}]")
}

/// Whether a hook command was generated by opensessions (any version).
///
/// Used to find and remove entries that older releases wrote at index 0 so
/// an upgrade does not leave a stale hook pointing at a dead server port,
/// without disturbing hooks that belong to other plugins.
pub fn is_opensessions_hook_command(command: &str) -> bool {
    const HOOK_PATHS: [&str; 6] = [
        "/focus",
        "/refresh",
        "/ensure-sidebar",
        "/pane-exited",
        "/client-resized",
        "/pane-layout-changed",
    ];
    if command.contains(SIDEBAR_PANE_TITLE) {
        return true;
    }
    [HTTP_HOOK_CURL_PREFIX, LEGACY_HTTP_HOOK_CURL_PREFIX]
        .iter()
        .flat_map(|prefix| command.split(prefix).skip(1))
        .filter_map(|rest| rest.split_whitespace().next())
        .filter(|url| url.starts_with("http://"))
        .any(|url| {
            let path = url.trim_start_matches("http://").split_once('/');
            let path = path.map(|(_, path)| format!("/{path}")).unwrap_or_default();
            let path = path.split('?').next().unwrap_or_default();
            HOOK_PATHS.contains(&path)
        })
}

/// Indices in a `show-hooks -g <hook>` listing whose command belongs to
/// opensessions. Lines look like `<hook>[<index>] <command>`; a hook with no
/// entries prints just its name.
pub fn owned_hook_indices(hook: &str, listing: &str) -> Vec<u32> {
    listing
        .lines()
        .filter_map(|line| {
            let rest = line.strip_prefix(hook)?.strip_prefix('[')?;
            let (index, command) = rest.split_once(']')?;
            let index = index.parse::<u32>().ok()?;
            is_opensessions_hook_command(command.trim_start()).then_some(index)
        })
        .collect()
}

/// `--noproxy '*'`: the server is on loopback, and an `http_proxy` in the tmux
/// server's environment would otherwise route (and, with a dead proxy, drop)
/// every hook request.
const HTTP_HOOK_CURL_PREFIX: &str =
    "curl -s -o /dev/null -m 0.2 --connect-timeout 0.1 --noproxy '*' -X POST ";
/// Prefix written by releases before `--noproxy`; still recognised so upgrades
/// remove the hooks those releases installed.
const LEGACY_HTTP_HOOK_CURL_PREFIX: &str =
    "curl -s -o /dev/null -m 0.2 --connect-timeout 0.1 -X POST ";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TmuxVar {
    PaneId,
    PaneTitle,
    PaneWidth,
    WindowPanes,
    SidebarWidthOption,
}

impl TmuxVar {
    fn name(self) -> &'static str {
        match self {
            Self::PaneId => "pane_id",
            Self::PaneTitle => "pane_title",
            Self::PaneWidth => "pane_width",
            Self::WindowPanes => "window_panes",
            Self::SidebarWidthOption => SIDEBAR_WIDTH_OPTION,
        }
    }

    pub fn format(self) -> TmuxFormat {
        TmuxFormat::var(self)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TmuxFormat {
    Var(TmuxVar),
    VarName(&'static str),
    Literal(String),
    Eq(Box<TmuxFormat>, Box<TmuxFormat>),
    Neq(Box<TmuxFormat>, Box<TmuxFormat>),
    Gt(Box<TmuxFormat>, Box<TmuxFormat>),
    And(Vec<TmuxFormat>),
}

impl TmuxFormat {
    pub fn var(var: TmuxVar) -> Self {
        Self::Var(var)
    }

    pub fn var_name(name: &'static str) -> Self {
        Self::VarName(name)
    }

    pub fn literal(value: impl Into<String>) -> Self {
        Self::Literal(value.into())
    }

    pub fn eq(left: TmuxFormat, right: TmuxFormat) -> Self {
        Self::Eq(Box::new(left), Box::new(right))
    }

    pub fn neq(left: TmuxFormat, right: TmuxFormat) -> Self {
        Self::Neq(Box::new(left), Box::new(right))
    }

    pub fn gt(left: TmuxFormat, right: TmuxFormat) -> Self {
        Self::Gt(Box::new(left), Box::new(right))
    }

    pub fn and(parts: impl IntoIterator<Item = TmuxFormat>) -> Self {
        let mut parts = parts.into_iter().collect::<Vec<_>>();
        if parts.len() == 1 {
            return parts.remove(0);
        }
        Self::And(parts)
    }

    pub fn render(&self) -> String {
        self.render_with_hash("#")
    }

    pub fn render_for_hook(&self) -> String {
        self.render_with_hash("##")
    }

    fn render_with_hash(&self, hash: &str) -> String {
        match self {
            Self::Var(var) => format!("{hash}{{{}}}", var.name()),
            Self::VarName(name) => format!("{hash}{{{name}}}"),
            Self::Literal(value) => value.clone(),
            Self::Eq(left, right) => format!(
                "{hash}{{==:{},{}}}",
                left.render_with_hash(hash),
                right.render_with_hash(hash)
            ),
            Self::Neq(left, right) => format!(
                "{hash}{{!=:{},{}}}",
                left.render_with_hash(hash),
                right.render_with_hash(hash)
            ),
            Self::Gt(left, right) => format!(
                "{hash}{{>:{},{}}}",
                left.render_with_hash(hash),
                right.render_with_hash(hash)
            ),
            Self::And(parts) => render_binary_operator(hash, "&&", parts),
        }
    }
}

fn render_binary_operator(hash: &str, operator: &str, parts: &[TmuxFormat]) -> String {
    match parts {
        [] => String::new(),
        [only] => only.render_with_hash(hash),
        [first, second] => format!(
            "{hash}{{{operator}:{},{}}}",
            first.render_with_hash(hash),
            second.render_with_hash(hash)
        ),
        [first, rest @ ..] => format!(
            "{hash}{{{operator}:{},{}}}",
            first.render_with_hash(hash),
            render_binary_operator(hash, operator, rest)
        ),
    }
}

/// Context the tmux hooks post to the server. The session is sent as its
/// `$N` id rather than its name: the body sits inside a single-quoted shell
/// argument, so a name containing `'` or `|` would break the hook. The server
/// resolves ids back to names (see `parse_context`).
pub fn hook_context_format() -> &'static str {
    "#{client_tty}|#{session_id}|#{window_id}|#{pane_id}|#{pane_active}"
}

pub fn http_hook_command(base: &str, path: &str, data: Option<&str>, background: bool) -> String {
    let body = data.map(|data| format!(" -d '{data}'")).unwrap_or_default();
    run_shell_command(
        &format!("{HTTP_HOOK_CURL_PREFIX}{base}{path}{body} >/dev/null 2>&1 || true"),
        background,
    )
}

pub fn delayed_http_hook_command(base: &str, path: &str) -> String {
    run_shell_command(
        &format!("sleep 0.05; {HTTP_HOOK_CURL_PREFIX}{base}{path} >/dev/null 2>&1 || true"),
        true,
    )
}

fn run_shell_command(script: &str, background: bool) -> String {
    let background = if background { " -b" } else { "" };
    format!("run-shell{background} \"{}\"", tmux_double_quote(script))
}

fn tmux_double_quote(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('$', "\\$")
}

pub fn sidebar_width_repair_pipeline() -> String {
    resize_sidebar_width_pipeline(sidebar_width_repair_filter())
}

pub fn close_orphan_sidebar_pipeline() -> String {
    format!(
        "tmux -S #{{socket_path}} list-panes -a -f '{}' -F '{}' | while IFS=$(printf '\\t') read -r session pane windows; do if [ \"$windows\" -le 1 ]; then fallback=$(tmux -S #{{socket_path}} list-sessions -F '{}' | awk -v s=\"$session\" '$0==s {{ if (prev != \"\") {{ print prev; exit }}; seen=1; next }} seen {{ print; exit }} {{ prev=$0 }}'); tmux -S #{{socket_path}} list-clients -t \"=$session:\" -F '{}' | while IFS= read -r client; do [ -n \"$client\" ] && [ -n \"$fallback\" ] && tmux -S #{{socket_path}} switch-client -c \"$client\" -t \"=$fallback:\" >/dev/null 2>&1 || true; done; fi; tmux -S #{{socket_path}} kill-pane -t \"$pane\" >/dev/null 2>&1 || true; done",
        orphan_sidebar_filter().render_for_hook(),
        orphan_sidebar_row_format(),
        TmuxFormat::var_name("session_name").render_for_hook(),
        TmuxFormat::var_name("client_tty").render_for_hook(),
    )
}

/// Hook body for `after-kill-pane` / `pane-exited`.
///
/// Ordering matters: the orphan sweep and the width repair run synchronously
/// so that by the time `kill-pane` returns, tmux has already given the freed
/// space to the remaining content pane rather than the sidebar. The server
/// notification runs in the background so a busy server never stalls tmux.
pub fn pane_exited_hook_command(base: &str) -> String {
    format!(
        "{} ; {} ; {}",
        run_shell_command(&close_orphan_sidebar_pipeline(), false),
        run_shell_command(&sidebar_width_repair_pipeline(), false),
        http_hook_command(base, "/pane-exited", None, true),
    )
}

/// Hook body for `pane-died` (a pane whose process exited under
/// `remain-on-exit`); same ordering rationale as [`pane_exited_hook_command`].
pub fn pane_died_hook_command(base: &str) -> String {
    format!(
        "{} ; {} ; {}",
        run_shell_command(&close_dead_content_pane_pipeline(), false),
        run_shell_command(&sidebar_width_repair_pipeline(), false),
        http_hook_command(base, "/pane-died", None, true),
    )
}

pub fn close_dead_content_pane_pipeline() -> String {
    let pane_title = TmuxVar::PaneTitle.format().render_for_hook();
    let pane_dead = TmuxFormat::var_name("pane_dead").render_for_hook();
    let window_id = TmuxFormat::var_name("window_id").render_for_hook();
    let session_name = TmuxFormat::var_name("session_name").render_for_hook();
    let session_windows = TmuxFormat::var_name("session_windows").render_for_hook();
    let client_tty = TmuxFormat::var_name("client_tty").render_for_hook();
    let pane_id = TmuxVar::PaneId.format().render_for_hook();

    // One `list-panes -a` pass classifies every window: windows whose only
    // live panes are sidebars get closed (switching attached clients to a
    // neighbour session first when it was the session's last window), and
    // dead panes are removed only inside windows that host a sidebar, so a
    // user's own `remain-on-exit` windows elsewhere are left alone.
    format!(
        "tmux -S #{{socket_path}} list-panes -a -F '{session_name}\t{window_id}\t{pane_title}\t{pane_dead}\t{session_windows}\t{pane_id}' | awk -F '\t' '{{ key=$1 \"\\t\" $2; session[key]=$1; window[key]=$2; windows[key]=$5; if ($3==\"opensessions-sidebar\") {{ sidebars[key]++ }} else if ($4!=\"1\") {{ live[key]++ }}; if ($4==\"1\") {{ dead[key]=dead[key] \" \" $6 }} }} END {{ for (key in session) {{ if (sidebars[key] > 0 && live[key]+0 == 0) print \"W\\t\" session[key] \"\\t\" window[key] \"\\t\" windows[key]; else if (sidebars[key] > 0 && dead[key] != \"\") print \"P\\t\" dead[key] }} }}' | while IFS=$(printf '\\t') read -r kind session window windows; do if [ \"$kind\" = W ]; then if [ \"$windows\" -le 1 ]; then fallback=$(tmux -S #{{socket_path}} list-sessions -F '{session_name}' | awk -v s=\"$session\" '$0==s {{ if (prev != \"\") {{ print prev; exit }}; seen=1; next }} seen {{ print; exit }} {{ prev=$0 }}'); tmux -S #{{socket_path}} list-clients -t \"=$session:\" -F '{client_tty}' | while IFS= read -r client; do [ -n \"$client\" ] && [ -n \"$fallback\" ] && tmux -S #{{socket_path}} switch-client -c \"$client\" -t \"=$fallback:\" >/dev/null 2>&1 || true; done; fi; tmux -S #{{socket_path}} kill-window -t \"$window\" >/dev/null 2>&1 || true; else for pane in $session; do tmux -S #{{socket_path}} kill-pane -t \"$pane\" >/dev/null 2>&1 || true; done; fi; done"
    )
}

fn orphan_sidebar_row_format() -> String {
    [
        TmuxFormat::var_name("session_name"),
        TmuxVar::PaneId.format(),
        TmuxFormat::var_name("session_windows"),
    ]
    .into_iter()
    .map(|format| format.render_for_hook())
    .collect::<Vec<_>>()
    .join("\t")
}

/// Resize every drifting sidebar pane back to `@opensessions_width`, but only
/// where that width is attainable: a sidebar spanning the whole window width
/// (stacked or zoomed layout) or a window narrower than width+2 cannot be
/// resized to the target, and since this pipeline runs from
/// `after-resize-pane`, retrying such a pane re-fires the hook forever.
///
/// Shell syntax note: tmux expands `$name` / `${name}` while parsing a hook
/// unless the `$` is escaped, so this must always be installed through
/// [`sidebar_width_repair_hook_command`], never wrapped by hand.
fn resize_sidebar_width_pipeline(filter: TmuxFormat) -> String {
    let read_width = "$(tmux -S #{socket_path} show-option -gqv @opensessions_width)";
    format!(
        "tmux -S #{{socket_path}} list-panes -a -f '{}' -F '{}' | awk -F '\t' -v w=\"{read_width}\" 'w != \"\" && $2 != $3 && $3 > w + 1 {{ print $1 }}' | xargs -n1 -I{{}} tmux -S #{{socket_path}} resize-pane -t {{}} -x \"{read_width}\"",
        filter.render_for_hook(),
        [
            TmuxVar::PaneId.format(),
            TmuxVar::PaneWidth.format(),
            TmuxFormat::var_name("window_width"),
        ]
        .iter()
        .map(TmuxFormat::render_for_hook)
        .collect::<Vec<_>>()
        .join("\t"),
    )
}

/// The width-repair pipeline as a background `run-shell` hook body, escaped
/// for tmux's hook parser.
pub fn sidebar_width_repair_hook_command() -> String {
    run_shell_command(&sidebar_width_repair_pipeline(), true)
}

fn sidebar_width_repair_filter() -> TmuxFormat {
    TmuxFormat::and([
        TmuxFormat::gt(TmuxVar::WindowPanes.format(), TmuxFormat::literal("1")),
        TmuxFormat::and([
            sidebar_pane_filter(),
            TmuxFormat::neq(
                TmuxVar::PaneWidth.format(),
                TmuxVar::SidebarWidthOption.format(),
            ),
        ]),
    ])
}

fn orphan_sidebar_filter() -> TmuxFormat {
    TmuxFormat::and([
        TmuxFormat::eq(TmuxVar::WindowPanes.format(), TmuxFormat::literal("1")),
        sidebar_pane_filter(),
    ])
}

fn sidebar_pane_filter() -> TmuxFormat {
    TmuxFormat::eq(
        TmuxVar::PaneTitle.format(),
        TmuxFormat::literal(SIDEBAR_PANE_TITLE),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn owned_hook_indices_only_match_opensessions_commands() {
        let base = "http://127.0.0.1:24500";
        let listing = format!(
            "after-select-window[0] {}\nafter-select-window[3] run-shell \"~/.tmux/plugins/other/hook.sh\"\nafter-select-window[{HOOK_SLOT}] {}\n",
            http_hook_command(base, "/ensure-sidebar", Some(hook_context_format()), true),
            http_hook_command(base, "/ensure-sidebar", Some(hook_context_format()), true),
        );

        assert_eq!(
            owned_hook_indices("after-select-window", &listing),
            vec![0, HOOK_SLOT]
        );
        assert_eq!(
            owned_hook_indices("after-select-window", "after-select-window\n"),
            Vec::<u32>::new()
        );
        // A different hook's listing never matches.
        assert_eq!(
            owned_hook_indices("session-created", &listing),
            Vec::<u32>::new()
        );
    }

    #[test]
    fn every_generated_hook_command_is_recognised_as_owned() {
        let base = "http://127.0.0.1:24500";
        for command in [
            http_hook_command(base, "/focus", Some(hook_context_format()), true),
            http_hook_command(base, "/refresh", None, true),
            delayed_http_hook_command(base, "/client-resized"),
            delayed_http_hook_command(base, "/pane-layout-changed"),
            pane_exited_hook_command(base),
            pane_died_hook_command(base),
            sidebar_width_repair_hook_command(),
        ] {
            assert!(is_opensessions_hook_command(&command), "{command}");
        }
        assert!(!is_opensessions_hook_command(
            "run-shell -b \"curl -s -o /dev/null -m 0.2 --connect-timeout 0.1 -X POST http://127.0.0.1:9/refresh-token\""
        ));
        assert!(!is_opensessions_hook_command(
            "run-shell \"~/.tmux/plugins/tmux-continuum/scripts/continuum_save.sh\""
        ));
    }

    #[test]
    fn renders_tmux_formats_once_or_escaped_for_hooks() {
        let filter = TmuxFormat::and([
            TmuxFormat::gt(TmuxVar::WindowPanes.format(), TmuxFormat::literal("1")),
            TmuxFormat::eq(
                TmuxVar::PaneTitle.format(),
                TmuxFormat::literal("opensessions-sidebar"),
            ),
        ]);

        assert_eq!(
            filter.render(),
            "#{&&:#{>:#{window_panes},1},#{==:#{pane_title},opensessions-sidebar}}"
        );
        assert_eq!(
            filter.render_for_hook(),
            "##{&&:##{>:##{window_panes},1},##{==:##{pane_title},opensessions-sidebar}}"
        );
    }

    #[test]
    fn renders_sidebar_width_repair_pipeline_without_call_site_hash_math() {
        let pipeline = sidebar_width_repair_pipeline();
        // Filter: only drifting sidebar panes in multi-pane windows.
        assert!(pipeline.contains(
            "list-panes -a -f '##{&&:##{>:##{window_panes},1},##{&&:##{==:##{pane_title},opensessions-sidebar},##{!=:##{pane_width},##{@opensessions_width}}}}' -F '##{pane_id}\t##{pane_width}\t##{window_width}'"
        ));
        // Attainability guard: skip full-width (stacked/zoomed) sidebars and
        // windows too narrow to hold width+2, so the hook cannot re-fire forever.
        let read_width = "$(tmux -S #{socket_path} show-option -gqv @opensessions_width)";
        assert!(pipeline.contains(&format!(
            "awk -F '\t' -v w=\"{read_width}\" 'w != \"\" && $2 != $3 && $3 > w + 1 {{ print $1 }}'"
        )));
        assert!(pipeline.ends_with(&format!("resize-pane -t {{}} -x \"{read_width}\"")));
        // tmux expands `$name` while parsing hooks; only `$(`/`$<digit>` may appear.
        assert!(!pipeline.contains("$w") && !pipeline.contains("${"));
        // The installed form escapes quotes and dollars for tmux's parser.
        let hook = sidebar_width_repair_hook_command();
        assert!(hook.starts_with("run-shell -b \""));
        assert!(hook.contains("-v w=\\\"\\$(tmux"));
        // Only the hook-level `#{socket_path}` is expanded by tmux; every other
        // format is escaped for the run-shell layer.
        assert!(!pipeline.contains(" #{pane_"));
    }

    #[test]
    fn renders_pane_exited_hook_with_orphan_close_before_server_cleanup() {
        let hook = pane_exited_hook_command("http://127.0.0.1:1234");

        assert!(hook.starts_with(
            "run-shell \"tmux -S #{socket_path} list-panes -a -f '##{&&:##{==:##{window_panes},1},##{==:##{pane_title},opensessions-sidebar}}'"
        ));
        assert!(
            hook.contains("switch-client -c \\\"\\$client\\\" -t \\\"=\\$fallback:\\\"")
                || hook.contains("switch-client -c \"\\$client\" -t \"=\\$fallback:\"")
        );
        assert!(
            hook.contains("kill-pane -t \\\"\\$pane\\\"")
                || hook.contains("kill-pane -t \"\\$pane\"")
        );
        // Width repair is synchronous and precedes the (background) server
        // notification, so `kill-pane` returns with the sidebar already fixed.
        let repair = run_shell_command(&sidebar_width_repair_pipeline(), false);
        let notify = http_hook_command("http://127.0.0.1:1234", "/pane-exited", None, true);
        assert!(hook.contains(&format!("{repair} ; {notify}")));
        assert!(hook.ends_with(&notify));
        assert!(notify.starts_with("run-shell -b "));
    }

    #[test]
    fn renders_pane_died_hook_that_notifies_the_died_endpoint_last() {
        let hook = pane_died_hook_command("http://127.0.0.1:1234");

        assert!(hook.starts_with("run-shell \"tmux -S #{socket_path} list-panes -a -F"));
        assert!(hook.contains(&run_shell_command(&sidebar_width_repair_pipeline(), false)));
        assert!(hook.ends_with(&http_hook_command(
            "http://127.0.0.1:1234",
            "/pane-died",
            None,
            true
        )));
    }
}
