#!/usr/bin/env bash
# Run opensessions from this checkout inside an isolated tmux server.
#
# The tmux socket is the isolation boundary: a server started with -L gets its
# own sessions, hooks, and key table, and opensessions derives its port and
# pid file from the socket path, so the copy started here never touches the
# tmux server (or the opensessions install) you normally use.
#
# Usage:
#   scripts/isolated-tmux.sh            # start/attach the "ostest" server
#   scripts/isolated-tmux.sh mysocket   # use another socket name
#   scripts/isolated-tmux.sh --stop     # kill the isolated server (and its opensessions)
#
# The isolated server loads your ~/.tmux.conf minus TPM/plugin lines, then this
# checkout's opensessions.tmux. Binaries come from target/release (falling back
# to target/debug), so build first: cargo build --release
#
# Shared with your normal setup on purpose: ~/.config/opensessions/config.json
# and session-order.json (so you test with your real settings) and the agent
# transcripts under ~/.claude, ~/.codex, ... (so real agents show up).
# Run this from a terminal window that is NOT inside your normal tmux; when
# it is, TMUX is cleared so nesting works, and the inner prefix becomes C-a.

set -eu

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOCKET="ostest"
STOP=0
for arg in "$@"; do
  case "$arg" in
    --stop) STOP=1 ;;
    *) SOCKET="$arg" ;;
  esac
done

if [ "$STOP" = 1 ]; then
  # opensessions notices its tmux server is gone and exits on its own within
  # a few seconds; kill-server also fires our pane-died cleanup first.
  tmux -L "$SOCKET" kill-server 2>/dev/null || true
  echo "isolated tmux server '$SOCKET' stopped"
  exit 0
fi

if [ ! -x "$ROOT/target/release/opensessions-server" ] && [ ! -x "$ROOT/target/debug/opensessions-server" ]; then
  echo "no local build found; run: cargo build --release" >&2
  exit 1
fi

CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/opensessions"
mkdir -p "$CONF_DIR"
CONF="$CONF_DIR/isolated-$SOCKET.tmux.conf"
{
  echo "# generated by scripts/isolated-tmux.sh; edit freely, regenerated on each start"
  if [ -f "$HOME/.tmux.conf" ]; then
    grep -vE "@plugin|/tpm/tpm|opensessions" "$HOME/.tmux.conf"
  fi
  if [ -n "${TMUX:-}" ]; then
    echo "set -g prefix C-a"
    echo "unbind C-b"
    echo "bind C-a send-prefix"
  fi
  echo "set-environment -g OPENSESSIONS_DEBUG_LOG /tmp/opensessions-$SOCKET-debug.log"
  echo "run-shell '$ROOT/opensessions.tmux'"
} >"$CONF"

# Use the local build instead of downloading a release bundle.
export OPENSESSIONS_SKIP_BINARY_DOWNLOAD=1
unset TMUX TMUX_PANE
echo "socket: $SOCKET   config: $CONF   debug log: /tmp/opensessions-$SOCKET-debug.log"
echo "prefix o → s opens the sidebar; stop everything with: $0 --stop"
exec tmux -L "$SOCKET" -f "$CONF" new-session -A -s dev -c "$ROOT"
